name: Manual Test Custom Template

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: wget google.com -O template.html
      - uses: ./
        with:
          token: ${{ secrets.SECURITY_TOKEN }}
          sarifReportDir: .
          templateFile: template.html
      - uses: actions/upload-artifact@v2
        with:
          name: reports
          path: ./*.pdf
