name: Manual Test Custom Template

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: wget https://www.w3schools.com/w3css/tryw3css_templates_parallax.htm -O template.html
      - uses: ./
        with:
          token: ${{ secrets.SECURITY_TOKEN }}
          templateFile: template.html
      - uses: actions/upload-artifact@v2
        with:
          name: reports
          path: ./*.pdf
